apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: project-gitops
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/quasar0x/project-gitops"
    targetRevision: HEAD
    path: helm-python-app
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
