replicaCount: 2
image:
  repository: dizevbije/project-gitops
  tag: 19896d7
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: false
serviceAccount:
  enabled: false
autoscaling:
  enabled: false
httpRoute:
  enabled: false
