replicaCount: 3
image:
  repository: dizevbije/project-gitops
  tag: be0e5f7
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: false
serviceAccount:
  enabled: false
autoscaling:
  enabled: false
httpRoute:
  enabled: false
